server:
  port: 8888
encrypt:
  key: myEncryptKey
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lisanlai/config_server_repo
#          searchPaths: '{application}'
        health:
          repositories:
            web-dev:
              name: web
              profiles: dev1
            interop:
              name: interop